#!/bin/bash

source "$(dirname "$(readlink -f "$0")")/config"

if [[ "$(docker images -q orangehrm/os-dev:php56 2>/dev/null)" == "" ]]; then
    printf "Building the image...\n\n"
    docker compose -f "$COMPOSE_FILE" -f "$COMPOSE_LEGACY_FILE" -f build php-5.6 nginx
fi

docker compose -f "$COMPOSE_FILE" -f "$COMPOSE_LEGACY_FILE" up -d php-5.6
