#!/bin/bash

source "$(dirname "$(readlink -f "$0")")/config"

if [[ "$(docker images -q orangehrm/os-dev:php81 2>/dev/null)" == "" ]]; then
    printf "Building the image...\n\n"
    docker compose -f "$COMPOSE_FILE" build php-8.1 nginx
fi

docker compose -f "$COMPOSE_FILE" up -d php-8.1
